### ISSUE TITLE
Add collector for OS information

### ISSUE THREAD

**Issue by erichte-ibm** [erichte-ibm/conga#8]
At the moment, this project is only intending to support Linux. There should be a collector to retrieve information about the given OS environment:
 - distribution & version
 - kernel version
 - ~scheduler?~

**Comment by dvelarde** [comment]
Not sure what I should be collecting for "scheduler?"

Also, I named my collector distro.rs, should I rename it to os.rs?

**Comment by erichte-ibm** [comment]
> Not sure what I should be collecting for "scheduler?"

Nevermind, looks like changing the process scheduler for the kernel is a lot more involved, and I was mixing up this with the I/O scheduler. Very unlikely someone will be hacking their kernel this way, and probably inferrable from the distro kernel if really needed. We might want to collect I/O scheduler in the future, but it's irrelevant for the types of benchmarking we will be doing.

> Also, I named my collector distro.rs, should I rename it to os.rs?

Discussed in meeting, but yes. Make sure the tags also match the file name, e.g. `"os.kernel_release"`

**Comment by erichte-ibm** [comment]
completed by #25
